
language: python
python:
  - 3.7
  - 3.8

cache:
  pip: true
  apt: true
  directories:
    - $HOME/.pip-cache
    - $HOME/.blender-cache

install:
  - scripts/install_blender.sh # requires https://stackoverflow.com/questions/42154912/permission-denied-for-build-sh-file
  - source .envs
  - pip install -e pkg_pytorch
  - pip install -r requirements_dev.txt
  - python -c "import blendtorch.btt as btt; print(btt.__version__)"
  - blender --background --python scripts/install_btb.py
  - blender --background --python-use-system-env --python-expr "import blendtorch.btb as btb; print(btb.__version__)"

script:
  - pytest tests -m background

notifications:
  email:
      on_success: never # change
      on_failure: never # always